<?php

use Phinx\Seed\AbstractSeed;

class LanguagesSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = array(
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Abkhazian',
                'iso2' => 'ab',
                'iso3' => 'abk',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Afar',
                'iso2' => 'aa',
                'iso3' => 'aar',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Afrikaans',
                'iso2' => 'af',
                'iso3' => 'afr',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Akan',
                'iso2' => 'ak',
                'iso3' => 'aka',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Albanian',
                'iso2' => 'sq',
                'iso3' => 'sqi',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Amharic',
                'iso2' => 'am',
                'iso3' => 'amh',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Arabic',
                'iso2' => 'ar',
                'iso3' => 'ara',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Aragonese',
                'iso2' => 'an',
                'iso3' => 'arg',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Armenian',
                'iso2' => 'hy',
                'iso3' => 'hye',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Assamese',
                'iso2' => 'as',
                'iso3' => 'asm',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Avaric',
                'iso2' => 'av',
                'iso3' => 'ava',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Avestan',
                'iso2' => 'ae',
                'iso3' => 'ave',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Aymara',
                'iso2' => 'ay',
                'iso3' => 'aym',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Azerbaijani',
                'iso2' => 'az',
                'iso3' => 'aze',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bambara',
                'iso2' => 'bm',
                'iso3' => 'bam',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bashkir',
                'iso2' => 'ba',
                'iso3' => 'bak',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Basque',
                'iso2' => 'eu',
                'iso3' => 'eus',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Belarusian',
                'iso2' => 'be',
                'iso3' => 'bel',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bengali',
                'iso2' => 'bn',
                'iso3' => 'ben',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bihari',
                'iso2' => 'bh',
                'iso3' => 'bih',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bislama',
                'iso2' => 'bi',
                'iso3' => 'bis',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bosnian',
                'iso2' => 'bs',
                'iso3' => 'bos',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Breton',
                'iso2' => 'br',
                'iso3' => 'bre',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Bulgarian',
                'iso2' => 'bg',
                'iso3' => 'bul',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Burmese',
                'iso2' => 'my',
                'iso3' => 'mya',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Catalan',
                'iso2' => 'ca',
                'iso3' => 'cat',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Chamorro',
                'iso2' => 'ch',
                'iso3' => 'cha',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Chechen',
                'iso2' => 'ce',
                'iso3' => 'che',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Chichewa',
                'iso2' => 'ny',
                'iso3' => 'nya',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Chinese',
                'iso2' => 'zh',
                'iso3' => 'zho',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Church Slavic',
                'iso2' => 'cu',
                'iso3' => 'chu',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Chuvash',
                'iso2' => 'cv',
                'iso3' => 'chv',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Cornish',
                'iso2' => 'kw',
                'iso3' => 'cor',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Corsican',
                'iso2' => 'co',
                'iso3' => 'cos',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Cree',
                'iso2' => 'cr',
                'iso3' => 'cre',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Croatian',
                'iso2' => 'hr',
                'iso3' => 'hrv',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Czech',
                'iso2' => 'cs',
                'iso3' => 'ces',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Danish',
                'iso2' => 'da',
                'iso3' => 'dan',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Divehi',
                'iso2' => 'dv',
                'iso3' => 'div',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Dutch',
                'iso2' => 'nl',
                'iso3' => 'nld',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Dzongkha',
                'iso2' => 'dz',
                'iso3' => 'dzo',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Esperanto',
                'iso2' => 'eo',
                'iso3' => 'epo',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Estonian',
                'iso2' => 'et',
                'iso3' => 'est',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Ewe',
                'iso2' => 'ee',
                'iso3' => 'ewe',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Faroese',
                'iso2' => 'fo',
                'iso3' => 'fao',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Fijian',
                'iso2' => 'fj',
                'iso3' => 'fij',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Finnish',
                'iso2' => 'fi',
                'iso3' => 'fin',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Fulah',
                'iso2' => 'ff',
                'iso3' => 'ful',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'English',
                'iso2' => 'en',
                'iso3' => 'eng',
                'is_active' => 1,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'French',
                'iso2' => 'fr',
                'iso3' => 'fra',
                'is_active' => 1,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Galician',
                'iso2' => 'gl',
                'iso3' => 'glg',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Ganda',
                'iso2' => 'lg',
                'iso3' => 'lug',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Georgian',
                'iso2' => 'ka',
                'iso3' => 'kat',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'German',
                'iso2' => 'de',
                'iso3' => 'deu',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Greek',
                'iso2' => 'el',
                'iso3' => 'ell',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'GuaranÃƒÆ’Ã',
                'iso2' => 'gn',
                'iso3' => 'grn',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Gujarati',
                'iso2' => 'gu',
                'iso3' => 'guj',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Haitian',
                'iso2' => 'ht',
                'iso3' => 'hat',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Hausa',
                'iso2' => 'ha',
                'iso3' => 'hau',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Hebrew',
                'iso2' => 'he',
                'iso3' => 'heb',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Herero',
                'iso2' => 'hz',
                'iso3' => 'her',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Hindi',
                'iso2' => 'hi',
                'iso3' => 'hin',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Hiri Motu',
                'iso2' => 'ho',
                'iso3' => 'hmo',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Hungarian',
                'iso2' => 'hu',
                'iso3' => 'hun',
                'is_active' => 0,
            ) ,
            array(
                'created_at' => date('Y-m-d H:i:s') ,
                'updated_at' => date('Y-m-d H:i:s') ,
                'name' => 'Icelandic',
                'iso2' => 'is',
                'iso3' => 'isl',
                'is_active' => 0,
            ) ,
        );

        $posts = $this->table('languages');
        $posts->insert($data)
              ->save();
    }
}
